steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/event-risk-processor', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/event-risk-processor']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - event-risk-processor
      - --image=gcr.io/$PROJECT_ID/event-risk-processor
      - --platform=managed
      - --region=southamerica-east1
      - --allow-unauthenticated
      - --memory=128Mi
      - --max-instances=1
      - --update-secrets=OPENAI_API_KEY=open-api-key:1
      - --set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,INPUT_TOPIC=input-topic,OUTPUT_TOPIC=output-topic

images:
  - gcr.io/$PROJECT_ID/event-risk-processor

options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/opportune-ruler-349816/locations/southamerica-east1/workerPools/cloudbuild-pool'